global:
  imageRegistry: aitutortansangdevacr.azurecr.io
  imageTag: latest
  environment: dev

backend:
  image: ai-tutor-backend
  replicas: 1
  port: 5000
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi
  env:
    NODE_ENV: production
    PORT: "5000"
    LOG_LEVEL: info

frontend:
  image: ai-tutor-frontend
  replicas: 1
  port: 80
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

redis:
  image: redis
  tag: "7-alpine"
  replicas: 1
  port: 6379

ingress:
  enabled: true
  className: nginx
  host: ""
  clusterIssuer: "letsencrypt-prod"
  tls:
    enabled: true
    secretName: "ai-tutor-tls"

auth:
  image: ai-tutor-auth
  replicas: 1
  port: 3001
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

learning:
  image: ai-tutor-learning
  replicas: 1
  port: 3002
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

assessment:
  image: ai-tutor-assessment
  replicas: 1
  port: 3003
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

ai-chat:
  image: ai-tutor-ai-chat
  replicas: 1
  port: 3004
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

ai-worker:
  image: ai-tutor-ai-chat
  replicas: 1
  command: ["node", "src/workers/aiWorker.js"]
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

aiQueue:
  attempts: 3
  backoffType: exponential
  backoffDelayMs: 2000
  removeOnComplete: 200
  removeOnFail: 500
  workerConcurrency: 2
  dlqName: ai-jobs-dlq
  dlqRetention: 2000
  dlqRemoveOnComplete: 200

keyvault:
  enabled: true
  name: "ai-tutor-dev-kv"
  tenantId: "01843f17-d034-4d59-a1e0-086d061bb770"
  clientId: "a345f191-4dc4-4e62-9db2-3a16b7c1b1cc"

seedData:
  enabled: false
  force: "false"
  dbName: learning_db
  backoffLimit: 2
  ttlSecondsAfterFinished: 86400
  imagePullPolicy: IfNotPresent

duckdns:
  enabled: false
  image: curlimages/curl:8.10.1
  schedule: "*/5 * * * *"
  domain: "ai-tutor-ts"
  tokenSecretName: duckdns-token
  tokenSecretKey: token
  ingressNamespace: ingress-nginx
  ingressServiceName: nginx-ingress-ingress-nginx-controller
