apiVersion: v1
kind: Service
metadata:
  name: ai-chat
  namespace: {{ .Values.global.environment }}
  labels:
    {{- include "ai-tutor.labels" . | nindent 4 }}
    app: ai-chat
spec:
  type: ClusterIP
  ports:
    - port: {{ index .Values "ai-chat" "port" }}
      targetPort: {{ index .Values "ai-chat" "port" }}
      protocol: TCP
      name: http
  selector:
    app: ai-chat
