apiVersion: v1
kind: Service
metadata:
  name: learning
  namespace: {{ .Values.global.environment }}
  labels:
    {{- include "ai-tutor.labels" . | nindent 4 }}
    app: learning
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.learning.port }}
      targetPort: {{ .Values.learning.port }}
      protocol: TCP
      name: http
  selector:
    app: learning
